---
# tasks file for builder

- name: Provisioning
  apt: name={{item}} state=installed
  with_items:
    - maven
    - git
- name: Clone a repo 
  git:
    repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
    dest: "{{ boxfuse_folder }}"

- name: Change the working directory and run maven package
  shell:
    chdir: "{{ boxfuse_folder }}"
    cmd: mvn package

- name: synchronize WAR step 1
  synchronize:
    mode: pull
    src: "{{ boxfuse_folder }}/target/hello-1.0.war"
    dest: ./hello-1.0.war
  delegate_to: localhost